### ISSUE TITLE
[bug]: Freepbx Core 17.0.18.4 Bug

### ISSUE THREAD

**Issue by VNP-PH** [FreePBX/issue-tracker#522] opened 2024-10-27 15:35 UTC
### FreePBX Version

FreePBX 17

### Issue Description

Once you upgrade to this version 17.0.18.4 PJSIP Carrier Registration no longer works.  freepbx will no long try to register. 17.0.17 works fine before upgrade.

### Operating Environment

Debian 12.7

**Comment by jcolp** [comment] 2024-10-27 22:23
This is a duplicate of #519

**Closed as not planned by jcolp** 2024-10-27 22:23 UTC
Labels: bug
