### ISSUE TITLE
[improvement]: running in unprivileged lxc containers

### ISSUE THREAD

**Issue by helmut1337** [FreePBX/issue-tracker#406] opened 2024-08-31 02:07 UTC
### FreePBX Version

FreePBX 17

### Improvement Description

hello team :)

I really like the installation script and also like to use it in unprivileged lxc containers on proxmox.
But since commit 91f53dbce501b8a88ec92a0361f7b532702f001c (Setup chrony for IPv4 only) the script is not working on unprivileged lcx containers anymore.
It fails at starting chrony.

Might there be another solution for the problem chrony is there to solve? Or maybe an option-parameter to optionally activate chrony on installation?

best regards
helmut

**Comment by kapilgupta01** [comment] 2024-09-02 04:33
Hi @helmut1337

**Comment by kapilgupta01** [comment] 2024-09-02 04:34
Hi @helmut1337 

91f53dbce501b8a88ec92a0361f7b532702f001c  fix is only to enable chrony for the ipv4 , previously it was enabled for ipv6 also so how this is breaking your installation? Could you please try to explain in bit more details?

Thanks

**Comment by countrynerd01** [comment] 2024-09-04 00:57
hi @kguptasangoma 

i am very new at this git hub thing. i can work my way around linux so please bear with me. I am also seeing an issue during installation script on a privileged and unprivileged Debian 12 Standard LXC. 

The installer goes as far as trying to get sysadmin17 to install and fails every time. i have tried several things on my own to fix anything that may be causing the error but cant seem to find the root cause or how to correct it.

what would you like me to provide you.

**Comment by kapilgupta01** [comment] 2024-09-04 03:48
Hi @countrynerd01 please share the installation log so we can see why sysadmin17 failed to install ?

Also what will happen if you manually try to install the sysadmin17 package
`apt install sysadmin17`

**Comment by countrynerd01** [comment] 2024-09-05 11:32
when i try to run apt install sysadmin17 apt cant located the package.

Here is the installer log. 
[freepbx17-install-2024.09.04-13.30.21.log](https://github.com/user-attachments/files/16891746/freepbx17-install-2024.09.04-13.30.21.log)

**Comment by volkjohn** [comment] 2024-09-10 00:20
Passing the `-x` flag to chronyd will allow you to run FreePBX in an unprivileged container.

     
>-x
>
>    This option disables the control of the system clock. chronyd will not try to make any adjustments of the clock. It will assume the clock is free running and still track its offset and frequency relative to the estimated true time. This option allows chronyd to be started without the capability to adjust or set the system clock (e.g. in some containers) to operate as an NTP server.
https://chrony-project.org/doc/4.3/chronyd.html

Edit the service file for chrony using the following:

`systemctl edit chrony`

Add this line immediately after the second line:

`ExecStart=!/usr/sbin/chronyd -x $DAEMON_OPTS`

Save, exit, and restart Chrony. Rerunning the FreePBX install script will allow it to finish without any problems.

**Comment by Alexander060101** [comment] 2024-09-14 14:52
> Edit the service file for chrony using the following:
> 
> `systemctl edit chrony`
> 
> Add this line immediately after the second line:
> 
> `ExecStart=!/usr/sbin/chronyd -x $DAEMON_OPTS`
> 
> Save, exit, and restart Chrony. Rerunning the FreePBX install script will allow it to finish without any problems.

Only adding this line resulted in error
`/etc/systemd/system/chrony.service.d/override.conf:1: Assignment outside of section. Ignoring.`
for me

Adding this
```
[Service]
ExecStart=!/usr/sbin/chronyd -x $DAEMON_OPTS
```
resulted in error
`chrony.service: Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.`
for me

Final solution for me was adding these 3 lines
```
[Service]
ExecStart=
ExecStart=!/usr/sbin/chronyd -x $DAEMON_OPTS
```

**Comment by Alexander060101** [comment] 2024-09-14 15:02
Hi @kguptasangoma 

Installing chrony on unprivileged LXC container will result in chrony service failing to start without the -x flag:
```
~$ sudo systemctl status chrony
× chrony.service - chrony, an NTP client/server
     Loaded: loaded (/lib/systemd/system/chrony.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-09-14 16:56:34 CEST; 21s ago
       Docs: man:chronyd(8)
             man:chronyc(1)
             man:chrony.conf(5)
    Process: 662 ExecStart=/usr/sbin/chronyd $DAEMON_OPTS (code=exited, status=1/FAILURE)
        CPU: 20ms

Sep 14 16:56:34 FreePBX17 systemd[1]: Starting chrony.service - chrony, an NTP client/server...
Sep 14 16:56:34 FreePBX17 chronyd[664]: chronyd version 4.3 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 -DEBUG)
Sep 14 16:56:34 FreePBX17 chronyd[662]: adjtimex(0x8001) failed : Operation not permitted
Sep 14 16:56:34 FreePBX17 chronyd[664]: Fatal error : adjtimex(0x8001) failed : Operation not permitted
Sep 14 16:56:34 FreePBX17 systemd[1]: chrony.service: Control process exited, code=exited, status=1/FAILURE
Sep 14 16:56:34 FreePBX17 systemd[1]: chrony.service: Failed with result 'exit-code'.
Sep 14 16:56:34 FreePBX17 systemd[1]: Failed to start chrony.service - chrony, an NTP client/server.
```

**Comment by countrynerd01** [comment] 2024-09-14 16:00
John Volk,

Thank you very much for this. Made that adjustment and ran the installer again and worked like a charm. The only other issue I have run into is freepbx gui is telling me that it wants me to disable a systemd service so that freepbx can control the network configuration.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kapilgupta01** [comment] 2024-09-16 04:43
Hi @countrynerd01 yes network configuration can either be managed by host machine networkd or by freepbx , trying to use both will not work, hence freepbx is giving information. 

Can we close this jira if everything is working fine for you?

**Closed as completed** 2024-10-15 04:14 UTC
Labels: improvement
