### ISSUE TITLE
[bug]: Refreshing keys fails

### ISSUE THREAD

**Issue by derekcrpd** [FreePBX/issue-tracker#189] opened 2024-05-28 12:33 UTC
### FreePBX Version

FreePBX 17

### Issue Description

My FreePBX log is filled with errors regarding gnupg attempting to refresh its keys. If I attempt to run the command manually from an SSH prompt I receive the following error: gpg: Fatal: status-fd is invalid: Bad file descriptor

If I remove the status-fd I then receive this error: gpg: conflicting commands

### Operating Environment

New install of FreePBX17 (about 2 weeks old now) on a fresh Debian 12 system.

### Relevant log output

```shell
Tried to refresh keys and failed with: GPG took too long to run the command: [/usr/bin/gpg --homedir /home/asterisk/.gnupg --no-permission-warning --keyserver-options auto-key-retrieve=true,timeout=10 --no-tty --status-fd 3 --keyserver hkp://keys.openpgp.org --refresh-keys 161311701A971B7A079B5604B8D612FDB2584FE1 D3BB883B19F0B2E7499AF98A48736170C7DAD6CD D38C1CB45FD92C463B371C6DF64CBBC153CD0B27 C5C26167A09555DB29DA4ECF06C57CED5C2FE148 EB312FC936875A7BC236DE6A36992456A6869B39 593E5D6A7107C285E698CB563C355822CCEBF9CB
```

**Comment by msanthosh18** [comment] 2024-05-28 12:51
Hi @derekcrpd ,
Can you please let us know how you landed this error.? since we are not experiencing the same.

**Comment by derekcrpd** [comment] 2024-05-28 12:59
I just happened to notice it in my FreePBX logs when I was investigating the issue with the CALL FLOW CONTROL. When I attempted to run the command manually it similarly failed.

refreshsignatures indicates that all signatures are "good".

**Comment by ramarajan222** [comment] 2024-05-28 13:33
Hi @derekcrpd ,

Can  you please try to run below command:

`/usr/bin/gpg --homedir /home/asterisk/.gnupg --no-permission-warning --keyserver-options auto-key-retrieve=true,timeout=10 --no-tty --status-file /tmp/file.txt --keyserver hkp://keys.openpgp.org --refresh-keys 161311701A971B7A079B5604B8D612FDB2584FE1 D3BB883B19F0B2E7499AF98A48736170C7DAD6CD D38C1CB45FD92C463B371C6DF64CBBC153CD0B27 C5C26167A09555DB29DA4ECF06C57CED5C2FE148 EB312FC936875A7BC236DE6A36992456A6869B39 593E5D6A7107C285E698CB563C355822CCEBF9CB`

NOTE: status-fd is nothing rather than the file descriptor to which output of command needs to be written. Since, that particular file fd is not present as of now in your status therefore manual command with --status-fd will fail. 

Please run the above command in order to see if the the Key refresh is working fine. You can check the status of the above command within /tmp/file.txt file

Please let us know the result for the same.

**Comment by derekcrpd** [comment] 2024-05-28 13:48
Yup, that works. I'm aware of  --status-fd, but not sure why whatever it is referencing does not exist since this is a new build. The only additional software that has been installed on this system is that which is required to make Amazon Polly work with the FreePBX tts, and nightly updates via apt. Other than that it is a brand new Debian 12 install with FreePBX installed on top of it via the installer.

gpg: refreshing 5 keys from hkp://keys.openpgp.org
gpg: key 86CE877469D2EAD9: "FreePBX Mirror 1 (Module Signing - 2014/2015) <security@freepbx.org>" not changed
gpg: key 3DDB2122FE6D84F7: "FreePBX Mirror 1 (Module Signing - 2016/2017) <security@freepbx.org>" not changed
gpg: key 9F9169F4B33B4659: "FreePBX Module Signing (This is the master key to sign FreePBX Modules) <modules@freepbx.org>" not changed
gpg: key 1588A7366BD35B34: "FreePBX Module Signing (This is the master key to sign FreePBX Modules) v2 <modules@freepbx.org>" not changed
gpg: key B53D215A755231A3: "FreePBX Mirror Servers <security@freepbx.org>" not changed
gpg: Total number processed: 5
gpg:              unchanged: 5

**Comment by kapilgupta01** [comment] 2024-06-04 13:38
We are not able to reproduce the similar error , sometime due to network , we do see GPG key timeout error.

**Closed as completed by kapilgupta01** 2024-06-04 13:38 UTC
Labels: bug, triage, needs-information
