### ISSUE TITLE
[bug]: Remote iCal calendars no longer working - exception Call to a member function getTimestamp() on array

### ISSUE THREAD

**Issue by adrianaditech** [FreePBX/issue-tracker#121] opened 2024-04-25 22:15 UTC
### FreePBX Version

FreePBX 16

### Issue Description

Using remote iCal calendar in the calendar module no longer works.
It no longer pulls events (even though the ical credentials and address are correct, work in other clients, and this used to work a few months ago in the PBX), and exception on trying to update the calendar in the admin configuration or change its settings
![image](https://github.com/FreePBX/issue-tracker/assets/95985011/6ddee4ad-7ad0-48b5-8bb8-85a1a523873a)

Attached screenshot

UI hangs completely then shows an exception after a minute of loading, when you try to edit a calendar.
All of these issues weren't present a few months ago.

### Operating Environment

PBXact UC25
Current PBX Version:16.0.40.7
Current System Version:12.7.8-2306-1.sng7  

Reboots do not help

**Comment by voggur** [comment] 2024-07-11 00:27
I upgraded from freepbx 15 to 16 and now I have the same problem.

**Comment by adrianaditech** [comment] 2024-07-11 02:15
@ sangoma - any update because this is also affecting commercial paying PBXact customers ?

**Comment by kapilgupta01** [comment] 2024-07-11 05:53
Hi All 

We are unable to reproduce this error so could you please share some more details steps to reproduce this issue. 
Looks like error is due to fetching the events from the upstream calendar so may be you can share your calendar configuration and as you are using pbxact so may be raise support ticket so we can ssh to your system to debug this issue directly.

thanks

**Comment by kapilgupta01** [comment] 2024-07-15 05:19
Hi @adrianaditech @voggur  Can you please share the steps to reproduce this issue? Please see my above comment for more information.

**Comment by kapilgupta01** [comment] 2024-07-18 04:42
Hi @adrianaditech @voggur Could you please share the steps?

Closing this jira as no feedback, feel free to re-open with the steps to reproduce this issue in-house. thanks

**Closed as completed by kapilgupta01** 2024-07-18 04:42 UTC
Labels: bug
