### ISSUE TITLE
[bug]: Error Setting up repositories

### ISSUE THREAD

**Issue by doczkal** [FreePBX/issue-tracker#70] opened 2024-04-01 16:30 UTC
### FreePBX Version

FreePBX 17

### Issue Description

execution of  ./sng_freepbx_debian_install.sh [--testing]

This fails with or without option --testing

### Operating Environment

System: 64-bit
Kernel version: 6.6
Debian version: 12 (bookworm)

### Relevant log output

```shell
2024-04-01 18:21:35 - Setting up repositories
--2024-04-01 18:21:35--  https://packages.sury.org/php/apt.gpg
Resolving packages.sury.org (packages.sury.org)... 169.150.247.39, 2400:52e0:1e00::1081:1
Connecting to packages.sury.org (packages.sury.org)|169.150.247.39|:443... failed: Connection timed out.
Connecting to packages.sury.org (packages.sury.org)|2400:52e0:1e00::1081:1|:443... failed: Network is unreachable.

# echo $?
4
```

**Comment by doczkal** [comment] 2024-04-01 16:39
Looks like the output is not as expected.

```
root@asterisk:/usr/local/src# lsb_release -sc 
No LSB modules are available.
bookworm
```

**Comment by ramarajan222** [comment] 2024-04-02 05:36
Hi @doczkal,

 Looks like the system failed to download the  "packages.sury.org/php/apt.gpg" key due to the network connection timed out.


Can you run the below command manually and then check it's working your system or not

`wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
`

**Comment by doczkal** [comment] 2024-04-02 09:15
Yeah, turned out that the routing of the VM is broken now. After Installation it was working fine.
I just installed the Debian 12 and executed ansible to clone the repository. But now I can connect via SSH (that's why I didn't think about routing issues in the first place) but all connection to the Internet fail. I have to debug this further.

**Comment by ramarajan222** [comment] 2024-04-03 12:35
Okay , thanks for the update, The issue is related to your network so moving to close this jira.

**Closed as completed by ramarajan222** 2024-04-03 12:35 UTC
Labels: bug, triage, needs-information
