### ISSUE TITLE
[bug]: freepbx 17 very long shutdown

### ISSUE THREAD

**Issue by Ressy66** [FreePBX/issue-tracker#563] opened 2024-11-25 01:21 UTC
### FreePBX Version

FreePBX 17

### Issue Description

17 takes a couple of minutes to exit freepbx/asterisk, this usually takes 10seconds  on v14
I have tried commenting out the systemd service file for "after http", makes no difference.

### Operating Environment

current up to date freepbx 17 and asterisk 21.5.0

### Relevant log output

```shell
Nov 25 10:40:19 sip01.REDACTED.net systemd[1]: Stopping chrony.service - chrony, an NTP client/server...
Nov 25 10:40:19 sip01.REDACTED.net systemd[1]: Stopping cron.service - Regular background program processing 
daemon...
Nov 25 10:40:19 sip01.REDACTED.net systemd[1]: Stopping fail2ban.service - Fail2Ban Service...
Nov 25 10:40:19 sip01.REDACTED.net systemd[1]: Stopping freepbx.service - FreePBX VoIP Server...
Nov 25 10:40:19 sip01.REDACTED.net systemd[1]: Stopping getty@tty1.service - Getty on tty1...
Nov 25 10:40:19 sip01.REDACTED.net haproxy[576]: [NOTICE]   (576) : haproxy version is 2.6.12-1+deb12u1
Nov 25 10:40:19 sip01.REDACTED.net haproxy[576]: [NOTICE]   (576) : path to executable is /usr/sbin/haproxy
Nov 25 10:40:19 sip01.REDACTED.net haproxy[576]: [WARNING]  (576) : Exiting Master process...
Nov 25 10:40:19 sip01.REDACTED.net haproxy[576]: [ALERT]    (576) : Current worker (746) exited with code 143 
(Terminated)
Nov 25 10:40:19 sip01.REDACTED.net haproxy[576]: [WARNING]  (576) : All workers exited. Exiting... (0)
Nov 25 10:40:19 sip01.REDACTED.net systemd[1]: Stopping haproxy.service - HAProxy Load Balancer...
Nov 25 10:40:19 sip01.REDACTED.net sshd[652]: Received signal 15; terminating.
Nov 25 10:40:19 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:40:19 41 [Warning] Aborted connection 41 to db: 
'asterisk' user: 'freepbxuser' host: 'localhost' (Got an error reading communication packets)
Nov 25 10:40:19 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:40:19 53 [Warning] Aborted connection 53 to db: 
'asterisk' user: 'freepbxuser' host: 'localhost' (Got an error reading communication packets)
Nov 25 10:40:19 sip01.REDACTED.net systemd[1]: Stopping icecast2.service - LSB: Icecast2 streaming media server.

Nov 25 10:40:19 sip01.REDACTED.net systemd[1]: apache2.service: Deactivated successfully.
Nov 25 10:40:19 sip01.REDACTED.net systemd[1]: Stopped apache2.service - The Apache HTTP Server.

Nov 25 10:40:19 sip01.REDACTED.net fwconsole[12897]: Running FreePBX shutdown...
Nov 25 10:40:19 sip01.REDACTED.net fwconsole[12897]: Running Asterisk pre from Cdrpro module
Nov 25 10:40:20 sip01.REDACTED.net fwconsole[12897]: Stopping CDRpro Service...
Nov 25 10:40:20 sip01.REDACTED.net fwconsole[12897]: Stopping CDRpro Service
Nov 25 10:40:20 sip01.REDACTED.net runuser[12994]: pam_unix(runuser:session): session opened for user 
asterisk(uid=999) by (uid=0)
Nov 25 10:40:20 sip01.REDACTED.net fail2ban-client[12896]: Shutdown successful
Nov 25 10:40:20 sip01.REDACTED.net systemd[1]: fail2ban.service: Deactivated successfully.
Nov 25 10:40:20 sip01.REDACTED.net systemd[1]: Stopped fail2ban.service - Fail2Ban Service.
Nov 25 10:40:20 sip01.REDACTED.net systemd[1]: fail2ban.service: Consumed 12.919s CPU time.

Nov 25 10:40:20 sip01.REDACTED.net runuser[13014]: pam_unix(runuser:session): session closed for user asterisk
Nov 25 10:40:20 sip01.REDACTED.net runuser[13025]: pam_unix(runuser:session): session opened for user 
asterisk(uid=999) by (uid=0)
Nov 25 10:40:20 sip01.REDACTED.net runuser[13025]: pam_unix(runuser:session): session closed for user asterisk
Nov 25 10:40:20 sip01.REDACTED.net runuser[13036]: pam_unix(runuser:session): session opened for user 
asterisk(uid=999) by (uid=0)
Nov 25 10:40:21 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:40:21 59 [Warning] Aborted connection 59 to db: 
'asterisk' user: 'freepbxuser' host: 'localhost' (Got an error reading communication packets)
Nov 25 10:40:21 sip01.REDACTED.net runuser[13036]: pam_unix(runuser:session): session closed for user asterisk
Nov 25 10:40:21 sip01.REDACTED.net runuser[13048]: pam_unix(runuser:session): session opened for user 
asterisk(uid=999) by (uid=0)
Nov 25 10:40:21 sip01.REDACTED.net runuser[13048]: pam_unix(runuser:session): session closed for user asterisk
Nov 25 10:40:21 sip01.REDACTED.net runuser[13059]: pam_unix(runuser:session): session opened for user 
asterisk(uid=999) by (uid=0)
Nov 25 10:40:21 sip01.REDACTED.net runuser[13059]: pam_unix(runuser:session): session closed for user asterisk
Nov 25 10:40:21 sip01.REDACTED.net fwconsole[12897]: Running Asterisk pre from Restapps module
Nov 25 10:40:21 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:40:21 60 [Warning] Aborted connection 60 to db: 
'asterisk' user: 'freepbxuser' host: 'localhost' (Got an error reading communication packets)
Nov 25 10:40:21 sip01.REDACTED.net runuser[13076]: pam_unix(runuser:session): session opened for user 
asterisk(uid=999) by (uid=0)
Nov 25 10:40:22 sip01.REDACTED.net runuser[13076]: pam_unix(runuser:session): session closed for user asterisk
Nov 25 10:40:22 sip01.REDACTED.net fwconsole[12897]: Stopping RestApps Server
Nov 25 10:40:22 sip01.REDACTED.net runuser[13092]: pam_unix(runuser:session): session opened for user 
asterisk(uid=999) by (uid=0)
Nov 25 10:40:22 sip01.REDACTED.net runuser[13092]: pam_unix(runuser:session): session closed for user asterisk
Nov 25 10:40:22 sip01.REDACTED.net runuser[13103]: pam_unix(runuser:session): session opened for user 
asterisk(uid=999) by (uid=0)
Nov 25 10:40:22 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:40:22 523 [Warning] Aborted connection 523 to db: 
'asterisk' user: 'freepbxuser' host: 'localhost' (Got an error reading communication packets)
Nov 25 10:40:22 sip01.REDACTED.net runuser[13103]: pam_unix(runuser:session): session closed for user asterisk
Nov 25 10:40:22 sip01.REDACTED.net runuser[13115]: pam_unix(runuser:session): session opened for user 
asterisk(uid=999) by (uid=0)
Nov 25 10:40:23 sip01.REDACTED.net runuser[13115]: pam_unix(runuser:session): session closed for user asterisk
Nov 25 10:40:23 sip01.REDACTED.net fwconsole[12897]: Stopped RestApps Server
Nov 25 10:40:23 sip01.REDACTED.net fwconsole[12897]: SangomaConnect Server is not running
Nov 25 10:40:23 sip01.REDACTED.net fwconsole[12897]: Running Asterisk pre from Sangomartapi module
Nov 25 10:40:24 sip01.REDACTED.net fwconsole[12897]: Stopping Sangoma RT API Server...
Nov 25 10:40:26 sip01.REDACTED.net fwconsole[12897]: Stopped Sangoma RT API Server
Nov 25 10:40:26 sip01.REDACTED.net fwconsole[12897]: Running Asterisk pre from Ucp module
Nov 25 10:40:27 sip01.REDACTED.net fwconsole[12897]: Stopping UCP Node Server
Nov 25 10:40:27 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:40:27 75 [Warning] Aborted connection 75 to db: 
'asterisk' user: 'freepbxuser' host: 'localhost' (Got an error reading communication packets)
Nov 25 10:40:28 sip01.REDACTED.net fwconsole[12897]: Stopped UCP Node Server
Nov 25 10:40:28 sip01.REDACTED.net fwconsole[12897]: Shutting down Asterisk Gracefully. Will forcefully kill after 
30 seconds.
Nov 25 10:40:28 sip01.REDACTED.net fwconsole[12897]: Press C to Cancel
Nov 25 10:40:28 sip01.REDACTED.net fwconsole[12897]: Press N to shut down NOW
Nov 25 10:40:28 sip01.REDACTED.net fwconsole[13254]: stty: 'standard input': Inappropriate ioctl for device
Nov 25 10:40:28 sip01.REDACTED.net fwconsole[13256]: stty: 'standard input': Inappropriate ioctl for device
Nov 25 10:40:33 sip01.REDACTED.net CRON[12815]: pam_unix(cron:session): session closed for user asterisk
Nov 25 10:41:28 sip01.REDACTED.net fwconsole[12897]: [>---------------------------] < 1 sec
Nov 25 10:41:28 sip01.REDACTED.net fwconsole[16080]: stty: 'standard input': Inappropriate ioctl for device
Nov 25 10:41:28 sip01.REDACTED.net fwconsole[12897]: Killing asterisk forcefully.
Nov 25 10:41:29 sip01.REDACTED.net fwconsole[12897]: Asterisk is still running and we can't stop it!
Nov 25 10:41:29 sip01.REDACTED.net systemd[1]: freepbx.service: Control process exited, code=exited, 
status=1/FAILURE
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: State 'stop-sigterm' timed out. Killing.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1649 (asterisk) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:42:59 48 [Warning] Aborted connection 48 to db: 
'asteriskcdrdb' user: 'freepbxuser' host: 'localhost' (Got an error reading communication packets)
Nov 25 10:42:59 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:42:59 0 [Note] /usr/sbin/mariadbd (initiated by: 
unknown): Normal shutdown
Nov 25 10:42:59 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:42:59 0 [Note] InnoDB: FTS optimize thread exiting.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1658 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1665 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1670 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1672 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1673 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1674 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1675 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1676 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1677 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1727 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1728 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1731 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1732 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1733 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1734 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1735 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1736 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1737 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1738 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1739 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1742 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1743 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1745 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1752 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1753 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1754 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1755 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1756 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1757 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1758 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1761 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1763 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1764 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1779 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1781 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1784 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1785 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1868 (asterisk) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 1894 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Killing process 13260 (n/a) with signal SIGKILL.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Failed with result 'exit-code'.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: Stopped freepbx.service - FreePBX VoIP Server.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: freepbx.service: Consumed 3min 7.981s CPU time.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: Stopped target network-online.target - Network is Online.
Nov 25 10:42:59 sip01.REDACTED.net systemd[1]: Stopping mariadb.service - MariaDB 10.11.6 database server...
Nov 25 10:42:59 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:42:59 0 [Note] InnoDB: Starting shutdown...
Nov 25 10:42:59 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:42:59 0 [Note] InnoDB: Dumping buffer pool(s) to 
/var/lib/mysql/ib_buffer_pool
Nov 25 10:42:59 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:42:59 0 [Note] InnoDB: Restricted to 2016 pages due 
to innodb_buf_pool_dump_pct=25
Nov 25 10:42:59 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:42:59 0 [Note] InnoDB: Buffer pool(s) dump completed 
at 241125 10:42:59
Nov 25 10:43:00 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:43:00 0 [Note] InnoDB: Removed temporary tablespace 
data file: "./ibtmp1"
Nov 25 10:43:00 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:43:00 0 [Note] InnoDB: Shutdown completed; log 
sequence number 185787861; transaction id 99609
Nov 25 10:43:00 sip01.REDACTED.net mariadbd[708]: 2024-11-25 10:43:00 0 [Note] /usr/sbin/mariadbd: Shutdown complete
Nov 25 10:43:00 sip01.REDACTED.net systemd[1]: mariadb.service: Deactivated successfully.
Nov 25 10:43:00 sip01.REDACTED.net systemd[1]: Stopped mariadb.service - MariaDB 10.11.6 database server.
Nov 25 10:43:00 sip01.REDACTED.net systemd[1]: mariadb.service: Consumed 14.110s CPU time.
```

**Comment by ccampbell118** [comment] 2024-11-25 18:05
I am having this issue as well as are a number of others apparently based on this forum thread. It seems to be particular to running FreePBX 17 in a VM with multiple types of hypervisors. 

https://community.freepbx.org/t/freepbx-17-slow-shutdown/99913

**Comment by lgaetz** [comment] 2024-11-25 18:08
this ticket possible duplication of https://github.com/FreePBX/issue-tracker/issues/439

**Comment by kapilgupta01** [comment] 2024-11-26 03:27
closing as duplicate of https://github.com/FreePBX/issue-tracker/issues/439

**Closed as completed by kapilgupta01** 2024-11-26 03:27 UTC
Labels: bug

**Comment by Ressy66** [comment] 2024-11-28 07:47
@ccampbell118 nope, this not a VM
