### ISSUE TITLE
[bug]: Not going to next agent if current one is available, keeps on ringing same agent in queue when using leastrecent strategy

### ISSUE THREAD

**Issue by dvlprDV** [FreePBX/issue-tracker#40] opened 2024-03-15 03:03 UTC
### FreePBX Version

FreePBX 16

### Issue Description

When using some of ringing strategies, for example "leastrecent" the call does not go to the next agent, if current agent is available, after a specified agent time. It works as expected when using "rrmemory" (possibly other strategies as well).

Please see this forum post that I started for more information: [https://community.freepbx.org/t/moving-to-next-extension-in-queue-even-when-available/94938/4](https://community.freepbx.org/t/moving-to-next-extension-in-queue-even-when-available/94938/4)

### Operating Environment

FreePBX 16.0.40.7
Asterisk 18.20.2

+---------------------+------------+---------+-------------+-----------+
| Module              | Version    | Status  | License     | Signature |
+---------------------+------------+---------+-------------+-----------+
| accountcodepreserve | 16.0.0.1   | Enabled | GPLv2       | Sangoma   |
| adv_recovery        | 16.0.43.8  | Enabled | Commercial  | Sangoma   |
| allowlist           | 16.0.4     | Enabled | GPLv3+      | Sangoma   |
| amd                 | 16.0.3     | Enabled | GPLv3+      | Sangoma   |
| announcement        | 16.0.6     | Enabled | GPLv3+      | Sangoma   |
| api                 | 16.0.13    | Enabled | AGPLv3+     | Sangoma   |
| areminder           | 16.0.16    | Enabled | Commercial  | Sangoma   |
| arimanager          | 16.0.13    | Enabled | GPLv3+      | Sangoma   |
| asterisk-cli        | 16.0.8     | Enabled | GPLv3+      | Sangoma   |
| asteriskinfo        | 16.0.10    | Enabled | GPLv3+      | Sangoma   |
| backup              | 16.0.69    | Enabled | GPLv3+      | Sangoma   |
| blacklist           | 16.0.21    | Enabled | GPLv3+      | Sangoma   |
| broadcast           | 16.0.18    | Enabled | Commercial  | Sangoma   |
| builtin             |            | Enabled |             | Unsigned  |
| bulkhandler         | 16.0.16    | Enabled | GPLv3+      | Sangoma   |
| calendar            | 16.0.21    | Enabled | GPLv3+      | Sangoma   |
| callaccounting      | 16.0.11    | Enabled | Commercial+ | Sangoma   |
| callback            | 16.0.4     | Enabled | GPLv3+      | Sangoma   |
| callerid            | 16.0.5     | Enabled | Commercial  | Sangoma   |
| callforward         | 16.0.5     | Enabled | AGPLv3+     | Sangoma   |
| calllimit           | 16.0.6     | Enabled | Commercial  | Sangoma   |
| callrecording       | 16.0.20    | Enabled | AGPLv3+     | Sangoma   |
| callwaiting         | 16.0.5     | Enabled | GPLv3+      | Sangoma   |
| cdr                 | 16.0.46.5  | Enabled | GPLv3+      | Sangoma   |
| cel                 | 16.0.18    | Enabled | GPLv3+      | Sangoma   |
| certman             | 16.0.22    | Enabled | AGPLv3+     | Sangoma   |
| cidlookup           | 16.0.15    | Enabled | GPLv3+      | Sangoma   |
| cloudmigration      | 16.0.18    | Enabled | Commercial  | Sangoma   |
| conferences         | 16.0.9     | Enabled | GPLv3+      | Sangoma   |
| conferencespro      | 16.0.9     | Enabled | Commercial  | Sangoma   |
| configedit          | 16.0.5     | Enabled | AGPLv3+     | Sangoma   |
| contactmanager      | 16.0.25    | Enabled | GPLv3+      | Sangoma   |
| core                | 16.0.68.20 | Enabled | GPLv3+      | Sangoma   |
| cos                 | 16.0.7     | Enabled | Commercial  | Sangoma   |
| customappsreg       | 16.0.5     | Enabled | GPLv3+      | Sangoma   |
| cxpanel             | 16.0.6     | Enabled | GPLv3       | Sangoma   |
| dahdiconfig         | 16.0.9     | Enabled | GPLv3+      | Sangoma   |
| dashboard           | 16.0.20    | Enabled | AGPLv3+     | Sangoma   |
| daynight            | 16.0.3     | Enabled | GPLv3+      | Sangoma   |
| dictate             | 16.0.1     | Enabled | GPLv3+      | Sangoma   |
| directory           | 16.0.3     | Enabled | GPLv3+      | Sangoma   |
| disa                | 16.0.4     | Enabled | AGPLv3+     | Sangoma   |
| donotdisturb        | 16.0.3     | Enabled | GPLv3+      | Sangoma   |
| dynroute            | 16.0.4     | Enabled | GPLv3+      | Sangoma   |
| endpoint            | 16.0.86.10 | Enabled | Commercial  | Sangoma   |
| extensionroutes     | 16.0.8     | Enabled | Commercial  | Sangoma   |
| extensionsettings   | 16.0.5     | Enabled | GPLv3+      | Sangoma   |
| fax                 | 16.0.13    | Enabled | GPLv3+      | Sangoma   |
| faxpro              | 16.0.11    | Enabled | Commercial  | Sangoma   |
| featurecodeadmin    | 16.0.11    | Enabled | GPLv3+      | Sangoma   |
| filestore           | 16.0.18    | Enabled | AGPLv3      | Sangoma   |
| findmefollow        | 16.0.23    | Enabled | GPLv3+      | Sangoma   |
| firewall            | 16.0.57.6  | Enabled | AGPLv3+     | Sangoma   |
| framework           | 16.0.40.7  | Enabled | GPLv2+      | Sangoma   |
| fw_langpacks        | 16.0.1     | Enabled | GPLv3+      | Sangoma   |
| hotelwakeup         | 16.0.9     | Enabled | GPLv2       | Sangoma   |
| iaxsettings         | 16.0.4     | Enabled | AGPLv3      | Sangoma   |
| infoservices        | 16.0.2     | Enabled | GPLv2+      | Sangoma   |
| iotserver           | 16.0.10.1  | Enabled | Commercial  | Sangoma   |
| irc                 | 16.0.1     | Enabled | GPLv3+      | Sangoma   |
| ivr                 | 16.0.9     | Enabled | GPLv3+      | Sangoma   |
| languages           | 16.0.4     | Enabled | GPLv3+      | Sangoma   |
| logfiles            | 16.0.7     | Enabled | GPLv3+      | Sangoma   |
| manager             | 16.0.21    | Enabled | GPLv2+      | Sangoma   |
| miscapps            | 16.0.2     | Enabled | GPLv3+      | Sangoma   |
| miscdests           | 16.0.1     | Enabled | GPLv3+      | Sangoma   |
| music               | 16.0.2     | Enabled | GPLv3+      | Sangoma   |
| oracle_connector    | 16.0.18    | Enabled | Commercial  | Sangoma   |
| outroutemsg         | 16.0.1     | Enabled | GPLv3+      | Sangoma   |
| paging              | 16.0.13    | Enabled | GPLv3+      | Sangoma   |
| pagingpro           | 16.0.10    | Enabled | Commercial  | Sangoma   |
| parking             | 16.0.4     | Enabled | GPLv3+      | Sangoma   |
| parkpro             | 16.0.5     | Enabled | Commercial  | Sangoma   |
| phonebook           | 16.0.3     | Enabled | GPLv3+      | Sangoma   |
| phpinfo             | 16.0.1     | Enabled | GPLv2+      | Sangoma   |
| pinsets             | 16.0.8     | Enabled | GPLv3+      | Sangoma   |
| pinsetspro          | 16.0.4     | Enabled | Commercial  | Sangoma   |
| pm2                 | 16.0.8     | Enabled | AGPLv3+     | Sangoma   |
| pms                 | 16.0.23    | Enabled | Commercial  | Sangoma   |
| presencestate       | 16.0.4     | Enabled | GPLv3+      | Sangoma   |
| printextensions     | 16.0.8     | Enabled | GPLv3+      | Sangoma   |
| queueprio           | 16.0.3     | Enabled | GPLv3+      | Sangoma   |
| queues              | 16.0.27    | Enabled | GPLv2+      | Sangoma   |
| queuestats          | 16.0.28    | Enabled | Commercial  | Sangoma   |
| qxact_reports       | 16.0.33    | Enabled | Commercial  | Sangoma   |
| recording_report    | 16.0.33    | Enabled | Commercial  | Sangoma   |
| recordings          | 16.0.16    | Enabled | GPLv3+      | Sangoma   |
| restapps            | 16.0.36.5  | Enabled | Commercial  | Sangoma   |
| ringgroups          | 16.0.11    | Enabled | GPLv3+      | Sangoma   |
| sangomaconnect      | 16.0.47.2  | Enabled | Commercial  | Sangoma   |
| sangomacrm          | 16.0.10.19 | Enabled | Commercial  | Sangoma   |
| sangomartapi        | 16.0.47.1  | Enabled | Commercial  | Sangoma   |
| setcid              | 16.0.3     | Enabled | GPLv3+      | Sangoma   |
| sipsettings         | 16.0.27    | Enabled | AGPLv3+     | Sangoma   |
| sipstation          | 16.0.27    | Enabled | Commercial  | Sangoma   |
| sms                 | 16.0.25    | Enabled | Commercial  | Sangoma   |
| soundlang           | 16.0.9     | Enabled | GPLv3+      | Sangoma   |
| superfecta          | 16.0.29    | Enabled | GPLv2+      | Sangoma   |
| sysadmin            | 16.0.41.20 | Enabled | Commercial  | Sangoma   |
| timeconditions      | 16.0.11    | Enabled | GPLv3+      | Sangoma   |
| tts                 | 16.0.3     | Enabled | GPLv3+      | Sangoma   |
| ttsengines          | 16.0.3     | Enabled | AGPLv3      | Sangoma   |
| ucp                 | 16.0.38.1  | Enabled | AGPLv3+     | Sangoma   |
| userman             | 16.0.44.6  | Enabled | AGPLv3+     | Sangoma   |
| vega                | 16.0.6     | Enabled | Commercial+ | Sangoma   |
| vmblast             | 16.0.11    | Enabled | GPLv3+      | Sangoma   |
| vmnotify            | 16.0.10    | Enabled | Commercial  | Sangoma   |
| voicemail           | 16.0.52    | Enabled | GPLv3+      | Sangoma   |
| voicemail_report    | 16.0.3     | Enabled | Commercial  | Sangoma   |
| voipinnovations     | 16.0.29    | Enabled | Commercial  | Sangoma   |
| vqplus              | 16.0.21    | Enabled | Commercial  | Sangoma   |
| weakpasswords       | 16.0.1     | Enabled | GPLv3+      | Sangoma   |
| webcallback         | 16.0.3     | Enabled | Commercial  | Sangoma   |
| webrtc              | 16.0.17    | Enabled | GPLv3+      | Sangoma   |
| xmpp                | 16.0.7     | Enabled | AGPLv3      | Sangoma   |
| zulu                | 16.0.19    | Enabled | Commercial  | Sangoma   |
+---------------------+------------+---------+-------------+-----------+

**Comment by ramarajan222** [comment] 2024-04-04 06:29
Hi @dvlprDV ,

The same behavior is on my test system as well when I set the strategy to "leastrecent" and looks like it is an expected behavior.

https://community.asterisk.org/t/queue-strategy-leastrecent-is-not-skipping-to-next-agent/82974

If you want to use "leastrecent" ring strategy only then you may need to enable auto-pause or you need to use the FreePBX "lazy member" feature.

https://sangomakb.atlassian.net/wiki/spaces/PG/pages/35521271/VQ+Plus+Options+in+Queues#Lazy-Members

**Comment by dvlprDV** [comment] 2024-04-04 06:37
Hi @ramarajan222 ,

Thanks for your reply. I wouldn't say it should be expected behavior (as it's not documented), but I see your point.

I didn't realise the commercial module has this implemented. I don't have it, but I'll investigate whether it's worthwhile using that for queue management.

**Comment by ramarajan222** [comment] 2024-04-04 12:54
moving to close, reopen if needed. thanks.

**Closed as completed** 2024-04-04 12:53 UTC
Labels: bug, triage, needs-information
